name: main
on:
  push:
    branches: master
    tags:
      - v*
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        run: |
          docker buildx build \
            -t onedr0p/radarr-exporter:${GITHUB_REF##*/} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -f ./build/package/Dockerfile \
            --push .
